# Permalinks
permalink: pretty

# Setup
title:               Samuel Molnár
url:                 https://samuelmolnar.com
base:

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Samuel Molnar
  url:               https://twitter.com/samuelmolnar
  github_url:        https://github.com/smolnar
  email:             molnar.samuel@gmail.com
  strava_url:        https://www.strava.com/athletes/24829340

# Custom vars
version:             1.0.0

# Markdown settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
